### ISSUE TITLE
Docker: failed to open ALSA device "default", no such file or directory when clicking play

### ISSUE THREAD

**Issue by alexc-wormhole** [volumio/Volumio2#2177]
Play count is also set to "NaN'

Ubuntu 21.04 (hirsute)

Container logs:

```
devbox_volumio      | verbose: ControllerMpd::sendMpdCommand play
devbox_volumio      | client: [0] process command "playlistinfo"
devbox_volumio      | client: [0] command returned 0
devbox_volumio      | client: [0] process command "idle"
devbox_volumio      | client: [0] command returned 1
devbox_volumio      | error: ControllerMpd::pushError: TypeError: Cannot read property 'split' of undefined
devbox_volumio      | client: [0] process command "play"
devbox_volumio      | playlist: play 0:"Guns N' Roses-Appetite For Destruction/12. Rocket Queen.mp3"
devbox_volumio      | client: [0] command returned 0
devbox_volumio      | decoder_thread: probing plugin mad
devbox_volumio      | decoder: audio_format=44100:24:2, seekable=true
devbox_volumio      | ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
devbox_volumio      | exception: Failed to open "Audio device" (alsa)
devbox_volumio      | exception: nested: Failed to open ALSA device "default": No such file or directory
devbox_volumio      | exception: Failed to open "Audio device" (alsa)
devbox_volumio      | exception: nested: Failed to open ALSA device "default": No such file or directory
devbox_volumio      | player: problems opening audio device while playing "Guns N' Roses-Appetite For Destruction/12. Rocket Queen.mp3"
devbox_volumio      | client: [0] process command "idle"

```

Docker compose file
```
    volumio:
      image: jbonjean/volumio
      privileged: true
      environment:
        - HOST=http://machine.lan:3000
      volumes:
        - /srv/music:/var/lib/mpd/music:ro
        - /srv/volumio/data:/data
      ports:
        - 3000:3000
      devices:
        - /dev/snd:/dev/snd
      restart: unless-stopped
```

Docker version:

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~21.04.2
 Built:             Fri Oct  1 03:50:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~21.04.2
  Built:            Fri Oct  1 02:50:01 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~21.04.3
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~21.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```
